export const  companyConstant ={
    SET_COMPANY :"SET_COMPANY",
    SELECT_COMPANY:"SELECT_COMPANY",
    REMOVE_SELECT_COMPANY:"REMOVE_SELECT_COMPANY",
    SET_STOCK: "SET_STOCK",
    INCREASE_TOTAL_AMOUNT:"INCREASE_TOTAL_AMOUNT",
    DECREASE_TOTAL_AMOUNT:"DECREASE_TOTAL_AMOUNT",
    SET_SELL_AMOUNT:"SET_SELL_AMOUNT",
    SLEECT_STOCK:"SLEECT_STOCK", 
    UPDATE_STOCKS:"UPDATE_STOCKS"
    
}